kind: PersistentVolumeClaim
apiVersion: v1
metadata:
	name: redis-slave-claom
	annotations:
    volume.beta.kubernetes.io/storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      